[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.13"
tokio = "1.36.0"
web3 = "0.19.0"
async-trait = "0.1.50"
serde_json = "1.0.114"
